# Brewfile - unified dev environment (Mac fleet standard)
# Last updated 2026-06-21 by Derek G. Weber
# Run: brew bundle --file=~/dotfiles/Brewfile

# ---- Taps ----
tap "hashicorp/tap"   # Terraform (Homebrew core dropped it after the BSL relicense)

# ---- Core CLI ----
brew "openssl@3"
brew "tree"
brew "ansible"
brew "awscli"
brew "azure-cli"
brew "bat"
brew "btop"
brew "csvkit"
brew "curl"
brew "diff-so-fancy"
brew "direnv"
brew "docker"
brew "docker-compose"
brew "exiftool"
brew "eza"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "helm"
brew "htop"
brew "jq"
brew "jsonlint"
brew "k6"
brew "kubernetes-cli"
brew "mas"
brew "ncdu"
brew "neovim"
brew "p7zip"
brew "pipx"
brew "pyenv"
brew "python@3.12"
brew "rename"
brew "rsync"
brew "screen"
brew "ssh-copy-id"
brew "starship"
brew "hashicorp/tap/terraform"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "trash"
brew "unar"
brew "vim"
brew "watch"
brew "wget"
brew "wrk"
brew "yq"

# ---- Zsh plugins ----
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

# ---- GUI casks ----
cask "chromedriver"
cask "claude-code"
cask "claude"
cask "ghostty"
cask "gcloud-cli"

# ---- Nerd Fonts ----
cask "font-0xproto-nerd-font"
cask "font-3270-nerd-font"
cask "font-bigblue-terminal-nerd-font"
cask "font-caskaydia-cove-nerd-font"
cask "font-caskaydia-mono-nerd-font"
cask "font-daddy-time-mono-nerd-font"
cask "font-departure-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-gohufont-nerd-font"
cask "font-hack-nerd-font"
cask "font-heavy-data-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "font-iosevka-term-slab-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-opendyslexic-nerd-font"
cask "font-proggy-clean-tt-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "font-space-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "font-terminess-ttf-nerd-font"
cask "font-ubuntu-mono-nerd-font"
cask "font-ubuntu-nerd-font"
cask "font-ubuntu-sans-nerd-font"

# ---- Mac App Store (Air-trimmed) ----
mas "Speedtest", id: 1153157709